export const iconsLisFiles = {
  azure: { name: 'Azure', filename: 'azure' },
  css: { name: 'CSS', filename: 'css' },
  fluentui: { name: 'Fluent Ui', filename: 'fluentui' },
  html: { name: 'HTML', filename: 'html' },
  illustrator: { name: 'Illustrator', filename: 'illustrator' },
  indesign: { name: 'InDesign', filename: 'indesign' },
  jest: { name: 'Jest', filename: 'jest' },
  js: { name: 'JavaScript', filename: 'js' },
  knockout: { name: 'Knockout.js', filename: 'knockout' },
  microsoft: { name: 'Microsoft', filename: 'microsoft' },
  mochajs: { name: 'Mocha.js', filename: 'mochajs' },
  mysql: { name: 'MySQL', filename: 'mysql' },
  nextjs: { name: 'Next.js', filename: 'nextjs' },
  planetscale: { name: 'PlanetScale', filename: 'planetscale' },
  postgresql: { name: 'PostgreSQL', filename: 'postgresql' },
  premierepro: { name: 'Premiere Pro', filename: 'premierepro' },
  rails: { name: 'Ruby on Rails', filename: 'rails' },
  react: { name: 'React', filename: 'react' },
  redis: { name: 'Redis', filename: 'redis' },
  redux: { name: 'Redux', filename: 'redux' },
  retool: { name: 'Retool', filename: 'retool' },
  selenium: { name: 'Selenium Webdriver', filename: 'selenium' },
  stripe: { name: 'Stripe', filename: 'stripe' },
  trpc: { name: 'tRPC', filename: 'trpc' },
  ts: { name: 'TypeScript', filename: 'ts' },
  turborepo: { name: 'Turborepo', filename: 'turborepo' },
  vercel: { name: 'Vercel', filename: 'vercel' },
  wordpress: { name: 'Wordpress', filename: 'wordpress' },
}

export type IconsLisType = keyof typeof iconsLisFiles
