// import classNames from 'classnames'
import { useState } from 'react'

import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'

import About from '@/components/about/About'
import WorkHistory from '@/components/work-history/WorkHistory'

// const inter = Inter({ subsets: ['latin'] })

// const arr = new Array(9).fill('').map((_, i) => `bg-purple-${i + 1}00`)

export default function Home() {
  // const [sat, setSat] = useState<number>(0)
  // const [bal, setBal] = useState<number>(0)

  // console.log(arr)

  return (
    <>
      <Head>
        <title>{`Ron's site 😊`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Icon /> */}
        <About />
        <WorkHistory />
      </main>
    </>
  )
}
