import type { IconsLisType } from "./icons-list-files";

// Human-readable names for icons that don't read well as their key.
const iconLabels: Partial<Record<IconsLisType, string>> = {
  arduino: "Arduino",
  azure: "Azure",
  c: "C",
  clerk: "Clerk",
  convex: "Convex",
  copilot: "Copilot",
  cpp: "C++",
  css: "CSS",
  gcp: "Google Cloud",
  git: "Git",
  github: "GitHub",
  golang: "Go",
  html: "HTML",
  illustrator: "Illustrator",
  indesign: "InDesign",
  java: "Java",
  javascript: "JavaScript",
  jest: "Jest",
  jira: "Jira",
  kotlin: "Kotlin",
  linkedin: "LinkedIn",
  facebook: "Facebook",
  mochajs: "Mocha",
  mysql: "MySQL",
  nextjs: "Next.js",
  photoshop: "Photoshop",
  planetscale: "PlanetScale",
  postgresql: "PostgreSQL",
  premierepro: "Premiere Pro",
  python: "Python",
  rails: "Ruby on Rails",
  react: "React",
  reactnative: "React Native",
  redis: "Redis",
  redux: "Redux",
  retool: "Retool",
  selenium: "Selenium",
  shadcn: "shadcn/ui",
  stripe: "Stripe",
  supabase: "Supabase",
  tailwind: "Tailwind CSS",
  trpc: "tRPC",
  turborepo: "Turborepo",
  typescript: "TypeScript",
  vercel: "Vercel",
  vite: "Vite",
  wordpress: "WordPress",
};

export const getIconLabel = (name: IconsLisType) => iconLabels[name] ?? name;
